# Generated by Django 5.2.15 on 2026-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_auditlog_alter_complaint_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="ac_brand",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="complaint",
            name="ac_capacity",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="complaint",
            name="ac_model",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="complaint",
            name="customer_address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="complaint",
            name="customer_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="complaint",
            name="customer_phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_under_warranty",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="sold_by",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
